name: books
description: Book Store


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  http: ^0.13.4
  url_launcher: ^6.1.5
  readmore: ^2.2.0
  flutter_bloc: ^8.1.1
  json_serializable: ^6.5.1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  json_annotation: ^4.5.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.11

flutter_native_splash:
  color: "ffffff"
  image: assets/splash.png

flutter:

  uses-material-design: true

  assets:
    - assets/

